#ifndef __KEBOARD_H
#define __KEBOARD_H
// reference to https://en.wikipedia.org/wiki/Keyboard_layout 
//The 104-key US QWERTY layout
enum KEY_CODE{ 
    EMPTY = 0    ,
    //F1 ~ F12 , pause ... insert  ignored
    SPACE        = 32 , // 32 , ascii table start of printable char
    EXCLAM       ,
    DOUBLE_QUOTE ,
    HASH         ,
    DOLLAR       ,
    PERCENT      ,
    AND          ,
    SINGLE_QUOTE ,
    LEFT_PAR     ,
    RIGHT_PAR    ,
    WILDCARD     ,
    ADD          ,
    COMMA        ,
    HYPHEN       ,
    DOT          ,
    SLASH        ,  /* / symbol */
    ZERO         ,
    ONE          ,
    TWO          ,
    THREE        ,
    FOUR         ,
    FIVE         ,
    SIX          ,
    SEVEN        ,
    EIGHT        ,
    NINE         ,
    COLON        ,
    SEMICOLON    ,
    LESS         ,
    EQU          ,
    LARGER       ,
    QUES         , 
    AT              ,
    A               ,
    B               ,
    C               ,
    D               ,
    E               ,
    F               ,
    G               ,
    H               ,
    I               ,
    J               ,
    K               ,
    L               ,
    M               ,
    N               ,
    O               ,
    P               ,
    Q               ,
    R               ,
    S               ,
    T               ,
    U               ,
    V               ,
    W               ,
    X               ,
    Y               ,
    Z               ,
    LEFT_BRACKET    ,
    BACK_SLASH      ,
    RIGHT_BRACKET   ,
    CARET            ,
    UNDERSCORE       ,
    ACUTE            ,
    // small case alphabet ignored
    LEFT_CURL = 123   ,
    PIPE              ,
    RIGHT_CURL        ,
    TILDE             ,
    // control characters
    ESC               ,
    F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,NUMLOCK,SCROLL,
    INSERT            ,
    DEL               ,
    BACKSPACE        ,
    TAB               ,
    CAPS              ,
    ENTER             ,
    SHIFT             ,
    CTRL              ,
    ALT               ,
    UP_RELEASE    ,
    LEFT_RELEASE  ,
    DOWN_RELEASE  ,
    RIGHT_RELEASE ,

    PRINTSCR,
    PRINTSCR_RELEASE,
    PAUSE
};
typedef enum KEY_CODE KEY_CODE;

void init_kb();
void kb_handler();
#endif